# Generated by Django 2.1.2 on 2018-10-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=140)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hours_start_time', models.TimeField()),
                ('hours_end_time', models.TimeField()),
                ('note', models.CharField(max_length=500)),
            ],
        ),
    ]
