# Generated by Django 2.1.2 on 2018-10-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
    ]
